export NotFound from './NotFound/NotFound';
export CaroHomepage from './CaroHomepage/CaroHomepage';
export CaroApp from './CaroApp/CaroApp';
export FacebookAuthCallBack from './Auth/FacebookAuthCallBack';
export Landing from './Landing/Landing';
export Spectate from './Spectate/Spectate';
export Profile from	'./Profile/Profile';
export Ranking from './Ranking/Ranking';
export Caro from './Caro/Caro';
